---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 'https://api.stackbit.com/project/60afa9eeb6462d0016093ecf/webhook/forestry'
sections:
- type: document
  path: _data/config.json
  label: Site Configuration
  templates:
  - config
- type: document
  path: index.md
  label: Home
  templates:
  - home
- type: document
  path: store.md
  label: Store
  templates:
  - store
- type: jekyll-pages
  label: Pages
  create: all
  exclude: '{README.md,LICENSE.md}'
  new_doc_ext: md
  templates:
  - advanced
  - category
  - product
upload_dir: images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
